#!/usr/bin/env python3


import argparse
from mevlib.maketable import make_table


# input arguments and usage messages

parser = argparse.ArgumentParser(description=(
    """Generates a lookup table given a description of chemical kinetics to """
    """be used for simulation of diffusion-limited reactions in pellets.    """
))
parser.add_argument(
    'fname', metavar='fname', type=str, help=(
        """Name of input file name. Currently only our own file format      """
        """(.sbl files) are supported, but others may be added in the       """
        """future.                                                          """
    )
)
parser.add_argument(
    '-v', '--verbose', action='store_true', help=(
        """Print additional information related to the parsing of generated """
        """files and generation of the lookup table.                        """
    )
)
parser.add_argument(
    '-k', '--keepnonreacting', action='store_true', help=(
        """By default nonreacting species are dropped from the resulting    """
        """transforms to save space.  Use this option to keep them instead. """
    )
)
parser.add_argument(
    '-o', '--outfile', type=str, default="mevlookup.f03", help=(
        """Name of output python file."""
    )
)
args = parser.parse_args()


make_table(
    args.fname, args.outfile,
    args.verbose, keepnonreacting=args.keepnonreacting
)


